/*Lucas Sequence
a = 0, b=0, c=1 are the 1st three terms. All other terms in the Lucas sequence are generated by the sum of their 3 
most recent predecessors. Write a program to generate the first n terms of a Lucas Sequence.

Input format:
The input containing an integer 'n' which denotes the given number

Output format:
Print the 'n' terms of the Lucas Sequence, separated by a single space. There are no leading or trailing spaces in 
the output.
*/
import java.util.Scanner;
public class Q3 {
	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		int n=sc.nextInt();
		int a=0,b=0,c=1;
		System.out.printf("%d %d %d ",a,b,c);
		while(n!=3 && n>1)
		{
			int d=a+b+c;
			System.out.printf("%d ",d);
			a=b;
			b=c;
			c=d;
			n--;
		}
	}
}
